// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1KTwhraWAr0BWkjHENNaP62EjysuUlNE',
    appId: '1:516523072594:web:de450fd2624a4068c9538b',
    messagingSenderId: '516523072594',
    projectId: 'fadi-app-bb8da',
    authDomain: 'fadi-app-bb8da.firebaseapp.com',
    storageBucket: 'fadi-app-bb8da.firebasestorage.app',
    measurementId: 'G-DYE2L7EZFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuUOEL4pZiH35ATyM4V-dA29_Y2NNU8LU',
    appId: '1:516523072594:android:881b0794bc3dab58c9538b',
    messagingSenderId: '516523072594',
    projectId: 'fadi-app-bb8da',
    storageBucket: 'fadi-app-bb8da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0-o2ea199srHYfEJhIRXfUX0FEHm1fFg',
    appId: '1:516523072594:ios:47c8982033906cf9c9538b',
    messagingSenderId: '516523072594',
    projectId: 'fadi-app-bb8da',
    storageBucket: 'fadi-app-bb8da.firebasestorage.app',
    iosBundleId: 'com.example.fadi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0-o2ea199srHYfEJhIRXfUX0FEHm1fFg',
    appId: '1:516523072594:ios:47c8982033906cf9c9538b',
    messagingSenderId: '516523072594',
    projectId: 'fadi-app-bb8da',
    storageBucket: 'fadi-app-bb8da.firebasestorage.app',
    iosBundleId: 'com.example.fadi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1KTwhraWAr0BWkjHENNaP62EjysuUlNE',
    appId: '1:516523072594:web:c35b3f84812b03d4c9538b',
    messagingSenderId: '516523072594',
    projectId: 'fadi-app-bb8da',
    authDomain: 'fadi-app-bb8da.firebaseapp.com',
    storageBucket: 'fadi-app-bb8da.firebasestorage.app',
    measurementId: 'G-91D2DZ021J',
  );
}
